leftnav:
- identifier: 3b14051d-76d9-8647-0fed-4f2ccdff1d7c
  name: Syllabus
  url: /pages/syllabus
  weight: 10
- identifier: d55121c0-3c92-030a-8d3b-f7928babe143
  name: Calendar
  url: /pages/calendar
  weight: 20
- identifier: 979d0a8f-4c6b-edab-341d-9492954cabb9
  name: Assignments
  url: /pages/assignments
  weight: 30
- identifier: de86ae57-1a7b-a7b8-8938-c263a907b65a
  name: Exams
  url: /pages/exams
  weight: 40
- identifier: b0f82ba0-83f9-9191-c238-8912122a3f99
  name: Projects
  url: /pages/projects
  weight: 50
- identifier: 815b4639-d71f-daeb-feb3-39b6d2315194
  name: Readings
  url: /pages/readings
  weight: 60
